title: "Welcome to Business Analytics Practicum (MGT 6214)!"
theme: jekyll-theme-cayman
description: "By Zhaohu (Jonathan) Fan <br /> ''Data drives decisions; analytics illuminates insights.''"
github:
  is_project_page: false
